<div class="card bg-white">
    <div class="card-body rounded-bottom p-4" id="">
        <h5 data-v-4cc4114b-s="">Institution overview</h5>
        <p data-v-4cc4114b-s="">About Palm Beach Currumbin State High <br data-v-4cc4114b-s=""> Palm Beach Currumbin State High School is located on the beautiful Gold Coast in South East Queensland.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> We offer you a caring, supportive and inclusive environment.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> We are proud of our record of academic, sporting and artistic achievement and we believe in recognising and celebrating hard work, effort and high achievement.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> As we are a large school, our many highly trained and experienced teachers deliver a wide range of diverse programs and opportunities including many that are not available at any other Gold Coast school.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> We use the latest technology including our aquaculture centre and laboratories.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> Our partnerships with Griffith University, Bond University and Southern Cross University provide you with unique and flexible pathways into tertiary education.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> About Education Queensland International (EQI)<br data-v-4cc4114b-s=""> Education Queensland International (EQI) develops and promotes programs for international students who want to study at a Queensland Government primary or secondary school.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> We are one of the largest provider of international student programs in Australia. We offer world-class education, a safe and healthy lifestyle in Queensland, unique cultural experiences and affordable living for our students.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> Our culturally diverse team provides help to ensure learning success and enjoyment for our students. Our school teachers, homestay providers and international coordinators care for, motivate and support our students.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> We have strong partnerships with Queensland’s top education providers. These partnerships help students to choose from many different higher education pathways. Students can even earn university credits while still at high school.<br data-v-4cc4114b-s=""><br data-v-4cc4114b-s=""> The Queensland Government invests in innovation and skills development in diverse industries. This forms strong partnerships with industry, universities, and researchers to inspire learning and connect students with innovation in the classroom.</p>
        <h5 data-v-4cc4114b-s="">Key selling points</h5>
        <p data-v-4cc4114b-s=""> Academic excellence </p>
        <p data-v-4cc4114b-s=""> Choice of subjects </p>
        <p data-v-4cc4114b-s=""> Pathways to university </p>
        <p data-v-4cc4114b-s=""> Study in sunny Queensland </p>
        <h5 data-v-4cc4114b-s="">Institution type</h5>
        <p data-v-4cc4114b-s="">School</p>
        <h5 data-v-4cc4114b-s="">University ownership</h5>
        <p data-v-4cc4114b-s="">Public</p>
    </div>
</div>